version: '3.7'

services:
  app:
    build:
      context: ../shop_backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../shop_backend/:/app/
    entrypoint: ["python", "manage.py", "runserver", "0:8000"]
